### ISSUE TITLE
Remove zip from repo

### ISSUE THREAD

**Issue by p5150j** [sunshine-cid/rpi-unbird#1]
@sunshine-cid Best practices normally dictate that non application assets (images, videos, zip files etc) should be hoisted on a CDN of some kind and kept away from repo code.

Possible CDN's
- AWS s3
- GCP bucket
- GoogleDrive
- DropBox
- IPFS

This way your `wget` isnt coupled to application repo.

**Comment by sunshine-cid** [comment]
Changes have been made to move files to a CDN, and the script has been updated to reflect those changes
