### ISSUE TITLE
Consider always executing sh scripts via make command 

### ISSUE THREAD

**Issue by p5150j** [sunshine-cid/rpi-unbird#2]
@sunshine-cid Consider always executing sh scripts via make command. This keeps things clean easy to digest and scalable/future-proof.

eg:
```
make install
make set-user
make [set-reset]-cron 
```

if you've never used it check this out https://www.youtube.com/watch?v=rKRG6oQf-bQ

**Comment by sunshine-cid** [comment]
Converted the script to Makefile. Issue resolved.
