### ISSUE TITLE
Use SCP or something else to upload audio files instead SAMBA server

### ISSUE THREAD

**Issue by jeremycook** [sunshine-cid/rpi-unbird#3]
A SAMBA server is overkill for getting files onto the PI, and increases the attack surface of a device that may be forgotten and doesn't receive updates.

Use SCP to upload to the server, or wget to download to the server.

**Comment by sunshine-cid** [comment]
Do you think it would be acceptable to provide instructions for SCP in the README, and set SAMBA to disabled by default?

**Comment by jeremycook** [comment]
At a minimum, SAMBA should be something you have to opt into. I think documenting using SCP in the readme would be helpful.

**Comment by sunshine-cid** [comment]
Changes have been made
